dist: xenial
sudo: false
jdk: openjdk8
install: true
language: java
rvm:
  - 2.2
  - jruby
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    - ariane-clh@hotmail.com
before_install:
  - chmod +x mvnw
